import './BG.scss'

export const metadata = {
    title: 'OJXacademy.com',
    description: 'Generated by create next app',
}

export default function Layout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="wrapperbg relative overflow-hidden bg-gray-950 max-sm:bg-gray-900">

            <div className="flex justify-center items-center" style={{ minHeight: "100vh" }}>
                <div className="container z-10">
                    {children}
                </div>
            </div>

            <div id="circlec" className="max-sm:hidden absolute h-[100vh] w-[100vh] rounded-full bg-cyan-500 blur-3xl opacity-50 bottom-[-25vh] left-[-25vh] z-0"></div>
            <div id="circlep" className="max-sm:hidden absolute h-[100vh] w-[100vh] rounded-full bg-purple-500 blur-3xl opacity-50 top-[-25vh] right-[-25vh] z-0"></div>
        </div>

    )
}
