import Navbar from './components/Navbar/Navbar'
import { UserContextProvider } from './contexts/userContext'
import './globals.css'

export const metadata = {
  title: 'OJXacademy.com',
  description: 'Generated by create next app',
  icons: {
    icon: "/icon.png"
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='text-white'>
        
        <UserContextProvider>
          <Navbar />

          <main>
            {children}
          </main>
        </UserContextProvider>

      </body>
    </html>
  )
}
